config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'companies#index'

  resources :companies, only: [:show, :index]
  resources :people, only: [:show]

  get 'favorites' => 'favorites#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :people
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show]
  before_action :set_favorites

  def index
    @companies = Company.all

    if current_user
      @fav_array = []
      @favorites.each do |fav|
        @fav_array << fav.name
      end
    end
  end

  def show
    @company_people = @company.people

    respond_to do |format|
      format.html {}
      format.js {}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    def set_favorites
      @favorites = current_user.favorites if current_user
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorites = current_user.favorites.all.order('created_at DESC')
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def show
    @person = Person.find(params[:id])
    respond_to do |format|
      format.html {}
      format.js {}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/index.html.slim
h1 Listing companies
- if current_user
  table.table
    thead
      tr
        th Title
        th Country
        th Добавить в избранное
        th

    tbody
      - @companies.each do |company|
        tr
          td = company.name
          td = Country.find_country_by_alpha2(company.country_code)
          td = link_to company, remote: true, id: "#{company.id}" do
            - if @fav_array.include?(company.name)
              span.glyphicon.glyphicon-star id="icon#{company.id}"
            - else
              span.glyphicon.glyphicon-star-empty id="icon#{company.id}"
          td = link_to 'Show', company
  br
- else
  p Для просмотра этой страницы вы должны зарегестрироваться!
  = link_to 'Войти |', new_user_session_path
  = link_to ' Зарегистрироваться', new_user_registration_path

app/views/companies/show.html.slim
h2 Title: "#{@company.name}"
hr
h3 Country: "#{@company.name}"
hr
h3 Country Code: "#{@company.country_code}"
hr
p Cписок сотрудников:
- if @company_people
  - @company_people.each do |person|
    i= "First name: #{person.first_name}, Last name: #{person.last_name}  "
    = link_to person, remote: true do
      - if @favorites.find_by(name: person.first_name)
        span.glyphicon.glyphicon-star id="icon#{person.id}"
      - else
        span.glyphicon.glyphicon-star-empty id="icon#{person.id}"
p
= link_to 'Back', companies_path

app/views/companies/show.js.erb
<% if current_user.favorites.find_by(name: @company.name) %>
  <% fav_id = current_user.favorites.find_by(name: @company.name).id %> // Если нашло компанию в избранном, получаем ее id и удаляем
  <% current_user.favorites.delete(fav_id) %>
  $("<%= escape_javascript("#icon#{@company.id}") %>").removeClass().addClass('glyphicon glyphicon-star-empty')
<% else %>
  <% current_user.favorites.create(name: @company.name) %>
  $("<%= escape_javascript("#icon#{@company.id}") %>").removeClass().addClass('glyphicon glyphicon-star')
<% end %>

app/views/favorites/index.html.slim
h1 Listing favorites
table.table
  thead
    tr
      th Избранное
  tbody
    - @favorites.each do |favorite|
      tr
        td = favorite.name

app/views/layouts/application.html.slim
doctype html
head
  title CompanyApp
  = stylesheet_link_tag    'application', media: 'all'
  = csrf_meta_tags
body
  .container
    /! Static navbar
    nav.navbar.navbar-default
      .navbar-header
        button.navbar-toggle data-target='.navbar-collapse' data-toggle='collapse' type='button'
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
        = link_to "My Website", root_path, class: 'navbar-brand'
      .navbar-collapse.collapse
        ul.nav.navbar-nav.navbar-right
          - if user_signed_in?
            li
              = link_to 'Избранное', favorites_path
            li
              = link_to "Выйти, #{current_user.email}", destroy_user_session_path, method: :delete
          - else
            li
              = link_to 'Войти', new_user_session_path
            li
              = link_to 'Зарегистрироваться', new_user_registration_path
        /! /.nav-collapse
    div
      - if flash[:notice]
        .alert.alert-success= flash[:notice]
      - if flash[:alert]
        .alert.alert-danger= flash[:alert]
      = yield
= javascript_include_tag 'application'

app/views/people/show.js.erb
<% if current_user.favorites.find_by(name: @person.first_name) %>
  <% fav_id = current_user.favorites.find_by(name: @person.first_name).id %> // Если нашло компанию в избранном, получаем ее id и удаляем
  <% current_user.favorites.delete(fav_id) %>
  $("<%= escape_javascript("#icon#{@person.id}") %>").removeClass().addClass('glyphicon glyphicon-star-empty')
<% else %>
  <% current_user.favorites.create(name: @person.first_name) %>
  $("<%= escape_javascript("#icon#{@person.id}") %>").removeClass().addClass('glyphicon glyphicon-star')
<% end %>